from pydantic import BaseModel, Field
from typing import Optional, Any

class ChatRequest(BaseModel):
    message: str = Field(..., description="The user's input message to the agent.")
    thread_id: str = Field(..., description="A unique identifier for the conversation session.")

class ChatResponse(BaseModel):
    status: str = Field(description="Status of the request (e.g. success, error)")
    answer: Optional[str] = Field(None, description="The final response generated by the agent.")
    error: Optional[str] = Field(None, description="Error message if status is error.")
